#!/bin/bash

# Updates /etc/webmin/virtual-server/config with settings that would be generated by the post-install wizard GUI
# Expects $1 to be a password for MySQL root user


declare CONFIG="/etc/webmin/virtual-server/config"

declare -i SYS_MEMORY=$(grep MemTotal /proc/meminfo|awk '{print $2}')/1000
declare MYSQL_MEMORY

if ((SYS_MEMORY < 512)); then
	MYSQL_MEMORY="small"
elif ((SYS_MEMORY < 1024)); then
	MYSQL_MEMORY="medium"
elif ((SYS_MEMORY < 2048)); then
	MYSQL_MEMORY="large"
elif ((SYS_MEMORY > 2047)); then
	MYSQL_MEMORY="huge"
fi


# Enable MySQL server
sed -i 's/mysql=.*/mysql=1/' $CONFIG

# Update password for MySQL root user
if [ ! -z "$1" ]; then
	virtualmin set-mysql-pass --user root --pass "$1", /etc/webmin/mysql/config
	echo "Updated root password for MySQL" >> ./calvin.log
fi

# Set MySQL server memory size
sed_param=s/mysql_size=.*/mysql_size=${MYSQL_MEMORY}/  
sed -i "$sed_param" $CONFIG
echo "MySQL memory setting is ${MYSQL_MEMORY}" >> ./calvin.log


# Enable preloading of virtualmin libraries
sed -i 's/preload_mode=.*/preload_mode=2/' $CONFIG
echo "Enabled Virtualmin library preloading" >> ./calvin.log

# Enable ClamAV server
sed -i 's/virus=.*/virus=1/' $CONFIG
echo "Enabled ClamAV server" >> ./calvin.log

# Enable SpamAssassin server
sed -i 's/spam=.*/spam=1/' $CONFIG
echo "Enabled SpamAssassin server" >> ./calvin.log

# Enable quotas
sed -i 's/quotas=.*/quotas=1/' $CONFIG
echo "Enabled quotas" >> ./calvin.log

# Enable hashed passwords
sed -i 's/hashpass=.*/hashpass=1/' $CONFIG
echo "Enabled hashed passwords" >> ./calvin.log

# Enable wizard_run flag
sed -i 's/wizard_run=.*/wizard_run=1/' $CONFIG
echo "Enabled wizard_run flag" >> ./calvin.log

echo "Virtualmin Post-Install Wizard setup complete" >> ./calvin.log



