#!/bin/bash

# Updates /etc/webmin/virtual-server/config with settings that would be generated by the post-install wizard GUI
# Expects $1 to be a password for MySQL root user


declare CONFIG="/etc/webmin/virtual-server/config"

declare -i SYS_MEMORY=$(grep MemTotal /proc/meminfo|awk '{print $2}')/1000
declare MYSQL_MEMORY

declare PREFIX="Calvin | virtualmin-post-install |"

if ((SYS_MEMORY < 512)); then
	MYSQL_MEMORY="small"
elif ((SYS_MEMORY < 1024)); then
	MYSQL_MEMORY="medium"
elif ((SYS_MEMORY < 2048)); then
	MYSQL_MEMORY="large"
elif ((SYS_MEMORY > 2047)); then
	MYSQL_MEMORY="huge"
fi


# Enable MySQL server
sed -i 's/mysql=.*/mysql=1/' $CONFIG

# Update password for MySQL root user
# This needs to be done BEFORE you upgrade to MariaDB 10.4+ due to the bug described at https://www.virtualmin.com/node/64694
if [ ! -z "$1" ]; then
	virtualmin set-mysql-pass --user root --pass "$1"
	echo "${PREFIX} Updated root password for MySQL" >> ./calvin.log
fi

# Set MySQL server memory size
sed_param=s/mysql_size=.*/mysql_size=${MYSQL_MEMORY}/  
sed -i "$sed_param" $CONFIG
echo "${PREFIX} MySQL memory setting is ${MYSQL_MEMORY}" >> ./calvin.log


# Enable preloading of virtualmin libraries
sed -i 's/preload_mode=.*/preload_mode=1/' $CONFIG
echo "${PREFIX} Enabled Virtualmin library preloading" >> ./calvin.log

# Enable ClamAV server
sed -i 's/virus=.*/virus=1/' $CONFIG
echo "${PREFIX} Enabled ClamAV server" >> ./calvin.log

# Enable SpamAssassin server
sed -i 's/spam=.*/spam=1/' $CONFIG
echo "${PREFIX} Enabled SpamAssassin server" >> ./calvin.log

# Enable quotas

# This is work in progress. Quotas need to be enabled in grub, which requires a bit of regex-fu beyond me. 
# I need to prepend `uquota,gquota,` to the rootflags parameter if it exists in GRUB_CMDLINE_LINUX, otherwise add it

# sudo grep -q "rootflags" /etc/default/grub && sudo sed -i "s/rootflags=/rootflags=uquota,gquota,/" /etc/default/grub || echo "rootflags not found"

# loosely converted from this snippet of https://github.com/virtualmin/virtualmin-gpl/blob/master/wizard-lib.pl

#	my %grub;
#	&read_env_file($grubfile, \%grub) ||
#		return &text('wizard_egrubfile', "<tt>$grubfile</tt>");
#	my $v = $grub{'GRUB_CMDLINE_LINUX'};
#	$v || return &text('wizard_egrubline', "<tt>GRUB_CMDLINE_LINUX</tt>");
#	if ($v =~ /rootflags=(\S+)/) {
#		$v =~ s/rootflags=(\S+)/rootflags=$1,uquota,gquota/;
#		}
#	else {
#		$v .= " rootflags=uquota,gquota";
#		}
#

# Update the config file to let it know quotas are enabled
#sed -i 's/quotas=.*/quotas=1/' $CONFIG

#echo "${PREFIX} Enabled quotas" >> ./calvin.log 

# Enable hashed passwords
sed -i 's/hashpass=.*/hashpass=1/' $CONFIG
echo "${PREFIX} Enabled hashed passwords" >> ./calvin.log

# Enable wizard_run flag
echo "wizard_run=1" >> $CONFIG
sed -i 's/wizard_run=.*/wizard_run=1/' $CONFIG
echo "${PREFIX} Manually added wizard_run flag" >> ./calvin.log

# Redirect non-SSL calls to the admin panel to SSL
sed -i 's/ssl_redirect=.*/ssl_redirect=1/' /etc/webmin/miniserv.conf
echo "${PREFIX} Enabled non-SSL to SSL redirect for Webmin panel" >> ./calvin.log

# Check config?

echo "${PREFIX} Virtualmin Post-Install Wizard setup complete" >> ./calvin.log



