$CPAN::Config = {
	'cpan_home' => '/root/.cpan',
	'version_timeout' => '15',
	'show_unparsable_versions' => '0',
	'makepl_arg' => '',
	'histfile' => '/root/.cpan/histfile',
	'unzip' => '/bin/unzip',
	'show_upload_date' => '0',
	'mbuild_install_build_command' => './Build',
	'yaml_load_code' => '0',
	'urllist' => [
		'http://cpan.etla.org/',
		'http://cpan.mirror.anlx.net/',
		'http://cpan.mirrors.uk2.net/',
		'http://mirror.bytemark.co.uk/CPAN/',
		'http://mirror.ox.ac.uk/sites/www.cpan.org/',
		'http://mirror.sov.uk.goscomb.net/CPAN/'
	],
	'trust_test_report_history' => '0',
	'gzip' => '/bin/gzip',
	'keep_source_where' => '/root/.cpan/sources',
	'yaml_module' => 'YAML',
	'prefer_installer' => 'MB',
	'build_requires_install_policy' => 'yes',
	'connect_to_internet_ok' => '1',
	'getcwd' => 'cwd',
	'prefer_external_tar' => '1',
	'make_install_make_command' => '/bin/make',
	'no_proxy' => '',
	'build_cache' => '100',
	'make_arg' => '',
	'wget' => '/bin/wget',
	'auto_commit' => '0',
	'patch' => '',
	'ftp_proxy' => '',
	'ftp_passive' => '1',
	'tar' => '/bin/tar',
	'inactivity_timeout' => '0',
	'use_sqlite' => '0',
	'scan_cache' => 'atstart',
	'mbuildpl_arg' => '',
	'halt_on_failure' => '0',
	'cache_metadata' => '1',
	'show_zero_versions' => '0',
	'term_ornaments' => '1',
	'prefs_dir' => '/root/.cpan/prefs',
	'build_dir_reuse' => '0',
	'shell' => '/bin/bash',
	'prerequisites_policy' => 'follow',
	'perl5lib_verbosity' => 'none',
	'make' => '/bin/make',
	'gpg' => '/bin/gpg',
	'mbuild_arg' => '',
	'applypatch' => '',
	'inhibit_startup_message' => '0',
	'load_module_verbosity' => 'none',
	'mbuild_install_arg' => '',
	'commandnumber_in_prompt' => '1',
	'check_sigs' => '0',
	'build_dir' => '/root/.cpan/build',
	'index_expire' => '1',
	'bzip2' => '/bin/bzip2',
	'test_report' => '0',
	'tar_verbosity' => 'none',
	'pager' => '/bin/less',
	'term_is_latin' => '1',
	'make_install_arg' => '',
	'histsize' => '100',
	'http_proxy' => ''
};

1;
__END__